# Generated by Django 6.0.2 on 2026-03-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_order_remove_phone_created_at_alter_phone_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Narxni $ da kiriting', max_digits=12),
        ),
    ]
