# Generated by Django 6.0.2 on 2026-03-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_alter_phone_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='Manzil kiritilmagan'),
        ),
    ]
