# Generated by Django 6.0.2 on 2026-03-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_order_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Telefon', 'verbose_name_plural': 'Telefonlar'},
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='Yetkazib berish manzili'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='Mijoz ismi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=20, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.TextField(verbose_name='Buyurtma qilingan telefonlar'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Umumiy summa ($)'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Brend'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.ImageField(upload_to='phones/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Telefon nomi'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi ($)'),
        ),
    ]
