# Generated by Django 6.0.2 on 2026-04-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_alter_order_options_alter_phone_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='installment_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nasiya muddati (oy)'),
        ),
        migrations.AddField(
            model_name='order',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Oylik to'lov"),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', "Naqd (To'liq to'lov)"), ('installment', "Nasiya (Muddatli to'lov)")], default='cash', max_length=20, verbose_name="To'lov turi"),
        ),
        migrations.AddField(
            model_name='phone',
            name='is_installment_available',
            field=models.BooleanField(default=True, verbose_name='Nasiya savdo mavjud'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default="Do'kondan olib ketish", verbose_name='Yetkazib berish manzili'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Umumiy summa'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Narxi (so'm)"),
        ),
    ]
