# Generated by Django 6.0.2 on 2026-04-06 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_order_installment_period_order_monthly_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (URL uchun)')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.AddField(
            model_name='phone',
            name='battery',
            field=models.IntegerField(default=5000, verbose_name='Batareya quvvati (mAh)'),
        ),
        migrations.AddField(
            model_name='phone',
            name='memory',
            field=models.IntegerField(default=128, verbose_name='Doimiy xotira (ROM)'),
        ),
        migrations.AddField(
            model_name='phone',
            name='ram',
            field=models.IntegerField(default=8, verbose_name='Operativ xotira (RAM)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.TextField(verbose_name='Buyurtma qilingan telefonlar (JSON)'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Brend'),
        ),
        migrations.AddField(
            model_name='phone',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='phones.category', verbose_name='Kategoriya'),
        ),
    ]
