# Generated by Django 6.0.2 on 2026-05-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_category_phone_battery_phone_memory_phone_ram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='category',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name="To'lov cheki"),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default="Do'kondan olib ketish", verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='order',
            name='installment_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='Muddat (oy)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.TextField(verbose_name='Mahsulotlar (JSON)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=50, verbose_name="To'lov turi"),
        ),
        migrations.AlterField(
            model_name='phone',
            name='battery',
            field=models.IntegerField(default=5000, verbose_name='Batareya (mAh)'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='is_installment_available',
            field=models.BooleanField(default=True, verbose_name='Nasiya mavjud'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='memory',
            field=models.IntegerField(default=128, verbose_name='Xotira (GB)'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='ram',
            field=models.IntegerField(default=8, verbose_name='RAM (GB)'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
